In [4]:
#Importation des packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

In [5]:
df = pd.read_csv("loan.csv")#Téléchargement de notre dataset
df.head(10)#affichage de 10 premières lignes

age  gender  occupation education_level marital_status  income  \
0   32    Male    Engineer      Bachelor's        Married   85000   
1   45  Female     Teacher        Master's         Single   62000   
2   28    Male     Student     High School         Single   25000   
3   51  Female     Manager      Bachelor's        Married  105000   
4   36    Male  Accountant      Bachelor's        Married   75000   
5   24  Female       Nurse     Associate's         Single   48000   
6   42    Male      Lawyer        Doctoral        Married  120000   
7   29  Female      Artist      Bachelor's         Single   38000   
8   37    Male          IT        Master's        Married   92000   
9   48  Female      Doctor        Doctoral        Married  180000   

   credit_score loan_status  
0           720    Approved  
1           680    Approved  
2           590      Denied  
3           780    Approved  
4           710    Approved  
5           640      Denied  
6           790    Approved  
7           620      Denied  
8           750    Approved  
9           820    Approved

In [ ]:
#On remarque et on distingue notre variable cible "Loan_status"

In [6]:
df.info()# AFfichage des informations générales sur nos variables

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              61 non-null     int64 
 1   gender           61 non-null     object
 2   occupation       61 non-null     object
 3   education_level  61 non-null     object
 4   marital_status   61 non-null     object
 5   income           61 non-null     int64 
 6   credit_score     61 non-null     int64 
 7   loan_status      61 non-null     object
dtypes: int64(3), object(5)
memory usage: 3.9+ KB


In [7]:
df.isna().sum()#pas de valeur manquante pour nos variable

age                0
gender             0
occupation         0
education_level    0
marital_status     0
income             0
credit_score       0
loan_status        0
dtype: int64

In [8]:
#affichage de valeurs unique de nos variables 
df["age"].unique()

array([32, 45, 28, 51, 36, 24, 42, 29, 37, 48, 55, 31, 26, 39, 44, 27, 34,
       41, 30, 53, 38, 25, 46, 33, 40, 35, 43, 49, 54, 47, 52, 50],
      dtype=int64)

In [11]:
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [13]:
df["occupation"].unique ()

array(['Engineer', 'Teacher', 'Student', 'Manager', 'Accountant', 'Nurse',
       'Lawyer', 'Artist', 'IT', 'Doctor', 'Consultant', 'Analyst',
       'Salesman', 'Marketing', 'Architect', 'Designer', 'Pharmacist',
       'Researcher', 'Professor', 'Pilot', 'Receptionist', 'Banker',
       'Writer', 'Chef', 'Veterinarian', 'Sales', 'HR', 'Electrician',
       'Realtor', 'Photographer', 'Editor', 'Programmer', 'Dentist',
       'Musician', 'Psychologist', 'Server', 'Software', 'Stylist'],
      dtype=object)

In [15]:
df["education_level"].unique()

array(["Bachelor's", "Master's", 'High School', "Associate's", 'Doctoral'],
      dtype=object)

In [16]:
df["marital_status"].unique()
   

array(['Married', 'Single'], dtype=object)

In [17]:
df["credit_score"].unique()

array([720, 680, 590, 780, 710, 640, 790, 620, 750, 820, 770, 690, 610,
       730, 760, 650, 740, 800, 700, 580, 630, 670, 600, 810, 570, 560,
       660, 830], dtype=int64)

In [18]:
df["income"].unique()

array([ 85000,  62000,  25000, 105000,  75000,  48000, 120000,  38000,
        92000, 180000, 110000,  68000,  42000,  78000,  95000,  52000,
        88000, 125000,  72000,  98000,  80000,  35000, 115000,  45000,
        60000,  70000,  90000,  55000,  65000,  40000, 140000,  30000,
       100000,  28000,  82000,  58000,  50000, 130000, 175000,  32000],
      dtype=int64)

In [19]:
df["loan_status"].unique()

array(['Approved', 'Denied'], dtype=object)

Notre jeu de donnée est propre sans valeur manquante et bien structuré. Il nous reste que à réaliser de l'encodage pour nos variable object pour les rendre numérique.